server:
  name: "salvo_demo_rbatis"
  address: "0.0.0.0:5800"
  ssl: false
  cors_allow_origin:
    - "https://salvo.rs"

database:
  database_url: "mysql://root:zjf1qaz!QAZ@100.64.0.8/test"

jwt:
  jwt_secret: "secret"
  jwt_exp: 6000

cert:
  cert: "config/certs/cert.pem"
  key: "config/certs/key.pem"

log:
  filter_level: "info"        # Available options: "debug", "info", "warn", "error"
  with_ansi: true
  to_stdout: true
  directory: "./logs"
  file_name: "my-service.log"
  rolling: "daily"            # Available options: "minutely", "hourly", "daily", "never"
